#!/usr/bin/env python

"""Run this script to have your mac speak out the steps of a seven minute workout"""

#Hi, I'm John

import sys, os
import time
import subprocess

voices = ['Daniel','Samantha']


# commands given to subprocess have to be a list of each keyword
# you don't include any spaces.
# example_command = ['say', '-v', 'Karen', 'Hello']
# subprocess.call(example_command)
# this will send the command to the terminal just as if you had typed:
# > say -v 'Karen' 'Hello'

# to use the timer for say, 10 seconds, do:
# time.sleep(10)

def say(s):
	a = time.time()
	subprocess.call(['say','-v','Samantha',s])
	b = time.time()
	return b-a
	
def workout():
	t = say('Begin jumping jacks')
	time.sleep(15)
	t = say('45 seconds to go')
	time.sleep(15-t)
	t = say('30 seconds')
	time.sleep(15-t)
	t = say('15 seconds')
	time.sleep(5-t)
	t = say('10 seconds. Wall sits coming up next.')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	t = say('Begin 10 second rest')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	
	t = say('Begin wall sit')
	time.sleep(15)
	t = say('45 seconds to go')
	time.sleep(15-t)
	t = say('30 seconds')
	time.sleep(15-t)
	t = say('15 seconds')
	time.sleep(5-t)
	t = say('10 seconds. Pushups coming up next.')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	t = say('Begin 10 second rest')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	
	t = say('Begin pushups')
	time.sleep(15)
	t = say('45 seconds to go')
	time.sleep(15-t)
	t = say('30 seconds')
	time.sleep(15-t)
	t = say('15 seconds')
	time.sleep(5-t)
	t = say('10 seconds. Crunches coming up next.')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	t = say('Begin 10 second rest')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	
	t = say('Begin crunches')
	time.sleep(15)
	t = say('45 seconds to go')
	time.sleep(15-t)
	t = say('30 seconds')
	time.sleep(15-t)
	t = say('15 seconds')
	time.sleep(5-t)
	t = say('10 seconds. Chair step-ups coming up next.')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	t = say('Begin 10 second rest')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	
	t = say('Begin chair step-ups')
	time.sleep(15)
	t = say('45 seconds to go')
	time.sleep(15-t)
	t = say('30 seconds')
	time.sleep(15-t)
	t = say('15 seconds')
	time.sleep(5-t)
	t = say('10 seconds. Squats coming up next.')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	t = say('Begin 10 second rest')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	
	t = say('Begin squats')
	time.sleep(15)
	t = say('45 seconds to go')
	time.sleep(15-t)
	t = say('30 seconds')
	time.sleep(15-t)
	t = say('15 seconds')
	time.sleep(5-t)
	t = say('10 seconds. Tricep dips coming up next.')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	t = say('Begin 10 second rest')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	
	t = say('Begin tricep dips')
	time.sleep(15)
	t = say('45 seconds to go')
	time.sleep(15-t)
	t = say('30 seconds')
	time.sleep(15-t)
	t = say('15 seconds')
	time.sleep(5-t)
	t = say('10 seconds. Plank coming up next.')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	t = say('Begin 10 second rest')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	
	t = say('Begin plank')
	time.sleep(15)
	t = say('45 seconds to go')
	time.sleep(15-t)
	t = say('30 seconds')
	time.sleep(15-t)
	t = say('15 seconds')
	time.sleep(5-t)
	t = say('10 seconds. High kneed running in place coming up next.')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	t = say('Begin 10 second rest')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	
	t = say('Begin high kneed running in place')
	time.sleep(15)
	t = say('45 seconds to go')
	time.sleep(15-t)
	t = say('30 seconds')
	time.sleep(15-t)
	t = say('15 seconds')
	time.sleep(5-t)
	t = say('10 seconds. Lunges coming up next.')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	t = say('Begin 10 second rest')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	
	t = say('Begin lunges')
	time.sleep(15)
	t = say('45 seconds to go')
	time.sleep(15-t)
	t = say('30 seconds')
	time.sleep(15-t)
	t = say('15 seconds')
	time.sleep(5-t)
	t = say('10 seconds. Pushups with rotation coming up next.')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	t = say('Begin 10 second rest')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	
	t = say('Begin pushups with rotation')
	time.sleep(15)
	t = say('45 seconds to go')
	time.sleep(15-t)
	t = say('30 seconds')
	time.sleep(15-t)
	t = say('15 seconds')
	time.sleep(5-t)
	t = say('10 seconds. Side plank coming up next.')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	t = say('Begin 10 second rest')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	
	t = say('Begin side plank')
	time.sleep(15)
	t = say('45 seconds to go')
	time.sleep(15-t)
	t = say('30 seconds')
	time.sleep(15-t)
	t = say('15 seconds')
	time.sleep(5-t)
	t = say('10 seconds. Almost done!')
	time.sleep(5-t)
	t = say('5')
	time.sleep(1-t)
	t = say('4')
	time.sleep(1-t)
	t = say('3')
	time.sleep(1-t)
	t = say('2')
	time.sleep(1-t)
	t = say('1')
	time.sleep(1-t)
	t = say('Workout complete. Good job!')

workout()
